config/routes.rb
require 'sidekiq/web'

PlayingWithData::Application.routes.draw do
  resources :bills, :except => [:edit, :destroy, :update]

  root :to => "bills#index"
  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/bill.rb
require 'csv'

class Bill < ActiveRecord::Base
  attr_accessible :csv, :csv_cache, :state

  has_many :calls, :dependent => :delete_all
  has_many :invalid_calls, :dependent => :delete_all

  mount_uploader :csv, BillUploader

  state_machine :initial => :new do
    event :run do
      transition :new => :processing
    end

    event :failed do
      transition :processing => :failed
    end

    event :complete do
      transition :processing => :complete
    end
  end

  def process_csv
    self.run

    CSV.open(self.csv.current_path, { :headers => :first_row, :header_converters => :symbol } ) do |csv|
      csv.each do |row|
        call = self.calls.build(row.to_hash)
        unless call.save
          self.calls.delete(call)

          invalid = self.invalid_calls.build(row.to_hash)

          invalid.error_messages = call.errors
          invalid.lineno = csv.lineno

          invalid.csv_source = row.to_s
          invalid.save
        end
      end
    end

    self.invalid_calls.any? ? self.failed : self.complete
  end

  validates :csv, :presence => true
end

app/models/call.rb
class Call < ActiveRecord::Base
  belongs_to :bill
  attr_accessible :source, :destination, :date, :time, :duration, :cost

  def duration=(val)
    result = nil
    begin
      result = val.to_s.split(/:/)
             .map { |t| Integer(t, 10) }
             .reverse
             .zip([60**0, 60**1, 60**2])
             .map { |i,j| i*j }
             .inject(:+)
    rescue ArgumentError, TypeError
    end
    write_attribute(:duration, result)
  end

  def time=(val)
    result = nil
    begin
      result = Time.parse(val)
    rescue ArgumentError, TypeError
    end
    write_attribute(:time, result)
  end

  # Handling Money:
  # http://stackoverflow.com/questions/1019939/ruby-on-rails-best-method-of-handling-currency-money
  # https://github.com/tobi/money_column

  validates_presence_of :source
  validates_presence_of :destination
  validates_presence_of :date,     :message => "is not a valid date"
  validates_presence_of :time,     :message => "is not a valid time"
  validates_presence_of :duration, :message => "is not a valid duration"
  validates :duration, :numericality => { :greater_than_or_equal_to => 0 }
  validates :cost, :presence => true,
                   :numericality => { :greater_than_or_equal_to => 0 }
end

app/models/invalid_call.rb
class InvalidCall < ActiveRecord::Base
  attr_accessible :cost, :date, :destination, :duration, :error_messages, :references, :source, :time

  serialize :error_messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  # GET /bills
  def index
    @bills = Bill.order("id DESC").all
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # POST /bills
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        BillsWorker.perform_async(@bill.id)
        format.html { redirect_to @bill }
      else
        format.html { render action: "new" }
      end
    end
  end

  # GET /bills/:id
  def show
    @bill = Bill.find(params[:id])

    @totals = {}
    if @bill.calls.any?
      @totals = summarize_calls_by_source(@bill.calls)
      @totals.merge!({ 'TOTAL' => summarize_calls(@bill.calls) })
    end
  end

  def summarize_calls(calls)
    calls.select("
      count(*) as count,
      sum(duration) as duration,
      sum(cost) as cost,
      avg(duration) as avg_duration,
      avg(cost) as avg_cost").first.attributes
  end

  def summarize_calls_by_source(calls)
    calls.group('source').select("
      source,
      count(*) as count,
      sum(duration) as duration,
      sum(cost) as cost,
      avg(duration) as avg_duration,
      avg(cost) as avg_cost").
      inject({}) { |r, totals|
        r[totals.source] = totals.attributes
        r
      }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
  def format_duration(duration)
    duration = duration.to_i
    return nil if duration < 0

    duration = duration.floor

    minutes, seconds = duration.divmod(60)
    hours, minutes = minutes.divmod(60)
    days, hours = hours.divmod(24)

    time = [hours,minutes,seconds].map { |v| v.to_s.rjust(2, "0") }.join(':')
    time = "#{days}d #{time}" if days != 0
    time
  end

  def generate_invalid_call_field(call, field)
    message = ""
    css_class = ""
    value = call.read_attribute(field)
    if call.error_messages[field].any?
        message = call.error_messages[field].join("\n")
        css_class = "alert alert-error"
    end
    content_tag('td', value, :class => css_class, :title => message)
  end
end

app/views/bills/_bill.html.erb
<div>
  <%= link_to "#{bill.csv.file.filename} #{time_ago_in_words(bill.created_at)} ago", bill %>
  <%
    label, css_class = 'New', 'label-info' if bill.new?
    label, css_class = 'Processing', 'label-warning' if bill.processing?
    label, css_class = 'Failed', 'label-important' if bill.failed?
  %>
  <%= content_tag('span', label, :class => ["label", css_class]) if label %>
</div>

app/views/bills/_complete.html.erb
    <h2>Reports</h2>
    <table>
      <thead>
        <tr>
          <th>Source Number</th>
          <th>Total Calls</th>
          <th>Total Duration</th>
          <th>Total Cost</th>
          <th>Average Duration</th>
          <th>Average Cost</th>
        </tr>
      </thead>
      <% @totals.each do |source, totals| %>
        <tr>
          <td><%= source %></td>
          <td><%= totals['count'] %></td>
          <td><%= format_duration(totals['duration']) %></td>
          <td><%= totals['cost'] %></td>
          <td><%= format_duration(totals['avg_duration']) %></td>
          <td><%= number_to_currency(totals['avg_cost']) %></td>
        </tr>
      <% end %>
    </table>

app/views/bills/_failed.html.erb
  <h2>Invalid Calls</h2>
    <table>
      <thead>
        <tr>
          <th>Line Number</th>
          <th>Source</th>
          <th>Destination</th>
          <th>Date</th>
          <th>Time</th>
          <th>Duration</th>
          <th>Cost</th>
        </tr>
      </thead>
      <% @bill.invalid_calls.each do |call| %>
        <tr>
          <td><%= call.lineno %></td>
          <%= generate_invalid_call_field(call, :source) %>
          <%= generate_invalid_call_field(call, :destination) %>
          <%= generate_invalid_call_field(call, :date) %>
          <%= generate_invalid_call_field(call, :time) %>
          <%= generate_invalid_call_field(call, :duration) %>
          <%= generate_invalid_call_field(call, :cost) %>
        </tr>
      <% end %>
    </table>

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div class="alert alert-error">
      <h3><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved</h3>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :csv %>
    <%= f.hidden_field :csv_cache %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/_new.html.erb
<div class="alert alert-info">
  <%= content_tag('span', "New", :class => ["label", "label-info"]) %>
  This bill is waiting to be processed. Please <%= link_to "refresh", @bill %> the page in a few minutes.
</div>

app/views/bills/_processing.html.erb
<div class="alert">
  <%= content_tag('span', "Processing", :class => ["label", "label-warning"]) %>
  This bill is currently being processed. Please <%= link_to "refresh", @bill %> the page in a few minutes.
</div>

app/views/bills/index.html.erb
<h1>Bills</h1>

<%= render @bills %>

app/views/bills/new.html.erb
<h1>Upload a Bill</h1>

<%= render 'form' %>

app/views/bills/show.html.erb
<h1>Bill <small>Uploaded <%= @bill.created_at.localtime.strftime("%l:%M%p %h %e %Y") %></small></h1>
<div>
  <%= link_to @bill.csv.file.filename, @bill.csv.url %><br>
  <%= content_tag('span', "Failed", :class => ["label", "label-important"]) if @bill.failed? %>
  <hr>
  <%= render @bill.state %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlayingWithData</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to 'Playing With Data', root_path, html_options = { class: "brand" } %>
        <div class="nav-collapse collapse">
          <ul class="nav pull-right">
            <li><%= link_to "New Bill", new_bill_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span12">
        <% if flash[:notice] %>
          <p class="alert alert-success"><%= flash[:notice] %></p>
        <% end %>
        <% if flash[:error] %>
          <p class="alert alert-error"><%= flash[:error] %></p>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="span12">
        <%= yield %>
      </div>
    </div>

    <hr>

    <footer>
      <p>&copy; Nobody 2012</p>
    </footer>

  </div> <!-- /container -->

</body>
</html>